enum AuthAction {
  CHANGE_EMAIL = 'AuthAction.CHANGE_EMAIL',
  CHANGE_PASSWORD = 'AuthAction.CHANGE_PASSWORD',
  CHANGE_NAME = 'AuthAction.CHANGE_NAME',
  TOGGLE_SERVER_ERROR = 'AuthAction.TOGGLE_SERVER_ERROR',
  TOGGLE_EMAIL_VALIDATION = 'AuthAction.TOGGLE_EMAIL_VALIDATION',
  TOGGLE_PASSWORD_VALIDATION = 'AuthAction.TOGGLE_PASSWORD_VALIDATION',
  TOGGLE_NAME_VALIDATION = 'AuthAction.TOGGLE_NAME_VALIDATION',
}

enum AuthMethod {
  LOGIN = 'AuthMethod.LOGIN',
  REGISTRATION = 'AuthMethod.REGISTRATION',
}

enum NewToDoAction {
  CHANGE_TEXT = 'NewToDoAction.CHANGE_TEXT',
  TOGGLE_TEXT_ERROR = 'NewToDoAction.TOGGLE_TEXT_ERROR',
}

export { AuthAction, AuthMethod, NewToDoAction };
